version: '3.5'

services:
  server1:
    build:
      context: ./C1
    image: server1:latest
    #image: tvillani/tp_apache_server:latest
    ports:
      - 80:80
      - 8080:8080
    container_name: container1_tp
    restart: always

  server2:
    build:
      context: ./C2
    image: server2:latest
    ports:
      - 8888:8888
    depends_on:
      - mariadb
    container_name: container2_tp
    restart: always
    #volumes:
    # - ./C2/sitios/:/var/www/ 

  mariadb:
    image: mariadb:10.5
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: ${USER_MDB}
      MYSQL_PASSWORD: ${USER_MDB_PASS}
      MYSQL_DATABASE: db_visitas
    container_name: container3_tp
    restart: always
    volumes:
      - ./C3:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8889:80
    container_name: container4_tp 
    environment:
      PMA_HOST: mariadb

volumes:
  db_volume:
    name: vol_persist